# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabiang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='menus',
            field=models.ManyToManyField(to='rabiang.Menu'),
        ),
    ]
