# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rabiang', '0003_auto_20160524_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 5, 23, 18, 58, 43, 551162, tzinfo=utc), max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(max_length=512),
        ),
    ]
