# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabiang', '0004_auto_20160524_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='menus',
            new_name='menu',
        ),
    ]
